
FROM node:18 AS builder
WORKDIR /app


COPY ./vuejs/package*.json ./
RUN npm install


COPY ./vuejs/ .
RUN npm run build


FROM nginx:stable-alpine


COPY --from=builder /app/dist /usr/share/nginx/html


COPY nginx.local.conf /etc/nginx/conf.d/default.conf


EXPOSE 80 443


CMD ["nginx", "-g", "daemon off;"]
